version: '3'

services:
  ntfy:
    image: binwiederhier/ntfy:v2.8.0
    restart: unless-stopped
    command: 
      - serve
    environment:
      TZ: UTC
      NTFY_CACHE_FILE: /etc/ntfy/cache.db
      NTFY_AUTH_FILE: /etc/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_ENABLE_LOGIN: true
    volumes:
      - configs:/etc/ntfy/
    ports:
      - 81:80
    networks:
      - ntfy
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s

  sms2ntfy:
    image: frnimh/sms2ntfy:latest
    restart: unless-stopped
    environment:
      NTFY_TOPIC: "messages"
      NTFY_PRIORITY: "3"
      NTFY_URL: "http://ntfy:80/"
      # NTFY_TOKEN: "Bearer tk_sampletoken"
    ports:
      - 8080:8080
    networks:
      - ntfy

networks:
  ntfy:
    name: ntfy

volumes:
  configs: